### ISSUE TITLE
Sortable/editable table

### ISSUE THREAD

**Issue by frmh0313** [pielab-uci/antidepressant-tapering#12]
## Todo
- [ ] Edits made in the projected schedule related to date should cascade to avoid any gaps between intervals.
- [ ] Always push back the following intervals rather than asking every time.
- [ ] Reflect in the table
- [ ] Reflect in the graph 
- [x] ~~Implement the ability to add a row in the table.~~
- [ ] When the user clicks on the edit schedule in the follow-up visit, they should be directed to the step 2 (table) and see a pop-up when clicking on the edit button in each row. The pop-up will include a lot of the same UI components in the step 1.

## Done
- [x] split interval column into start date and end date
- [x] Set related properties of antd Table
- [x] Make it sortable with drug name, start date, and end date
- [x] If users made an edit of dosage in a single interval, the rest of the intervals won’t be affected.
- [x] For cross-tapering scenario, let’s specify different medications in different colors in the table (e.g., red and green).
- [x] For cross-tapering scenario, it would be great if the table is sortable by medication.
- [x] Split the interval into two columns: one for the start date, the other for the end date. (Came up after the meeting)
- [x] Selected interval in the projected schedule should be included in the total number of pills.
- [x] Edits made in the projected schedule (if they are selected) should be reflected to the total number of pills.

- [x] Make dosage editable by typing number on click the cell, still displaying results in mg
- [x] Make start and end date editable using Date picker: refer to https://stackoverflow.com/questions/63248648/react-antt-design-editable-table-to-add-date-picker-not-working 
- [x] Table edit - chart sync

**Comment by frmh0313** [comment]
![image](https://user-images.githubusercontent.com/12432445/120029561-21a97a80-bfab-11eb-91f8-8e877cdc4379.png)

**Comment by frmh0313** [comment]
Plan 
- [ ] Make dosage editable by typing number on click the cell, still displaying results in mg
- [ ] Make start and end date editable using Date picker: refer to https://stackoverflow.com/questions/63248648/react-antt-design-editable-table-to-add-date-picker-not-working

**Comment by frmh0313** [comment]
Implemented giving different colors to different medications - but couldn't override the style settings for the row selected or hovered.

**Comment by frmh0313** [comment]
Decided to use AgGrid for the table component.

**Comment by frmh0313** [comment]
- [ ] Keep the selected rows selected after making changes in prescription
